### ISSUE TITLE
how to access my home network from outside

### ISSUE THREAD

**Issue by ghost** [alext-mkrs/meta-alext-edison#1]
https://communities.intel.com/message/361045

Thank's Alex'T

I installed perl-module-sys-hostname and now I have new error (Can't locate IO/Socket.pm)

root@neuberfran:~# opkg install perl-module-sys-hostname
Installing perl-module-sys-hostname (5.20.0-r1) on root.
Downloading http://repo.opkg.net/edison/repo/core2-32/perl-module-sys-hostname_5.20.0-r1_core2-32.ipk.
Configuring perl-module-sys-hostname.
root@neuberfran:~# ddclient -v
Can't locate IO/Socket.pm in @INC (you may need to install the IO::Socket module) (@INC contains: /etc/perl /usr/lib/perl/site_perl/5.20.0/ /usr/lib/perl/site_perl/5.20.0 /usr/lib/perl/vendor_perl/5.20.0/ /usr/lib/perl/vendor_perl/5.20.0 /usr/lib/perl/5.20.0/ /usr/lib/perl/5.20.0 /usr/local/lib/site_perl /usr/lib/perl/5.20.0 .) at /usr/sbin/ddclient line 27.
BEGIN failed--compilation aborted at /usr/sbin/ddclient line 27.

The other solution (for the future) is that : http://mkaczanowski.com/golang-build-dynamic-dns-service-go/

But I have error with NSUPDATE package

root@neuberfran:~# opkg install nsupdate
Unknown package 'nsupdate'.
Collected errors:
- opkg_install_cmd: Cannot install package nsupdate.

**Comment by alext-mkrs** [comment]
As I mentioned in the other thread - this is a topic for the community forum and not this repo.
Please use this one only to post new package requests - or better yet, use a dedicated thread in the community forum.

The error you present is "there's no such package in the repo", which is not an issue, because I haven't place one there.
